version: '3.4'

services:
  basestore:
    image: ${DOCKER_REGISTRY-}basestore
    build:
      context: .
      dockerfile: BaseStore/Dockerfile
 

  clientstore.angular.app:
    image: ${DOCKER_REGISTRY-}clientstoreangularapp
    build:
      context: .
      dockerfile: BaseStore/ClientApp/Dockerfile
    ports:
      - "4200:4200" 
      - "49153:49153"
    volumes:
      - ./BaseStore/ClientApp:/app